[project]
name= "website-scraper"
 version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "playwright>=1.48.0",
]

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "ruff",
]